language: android
sudo: true
android:
  components:
  - build-tools-28.0.3
  - android-15
  - android-28
  - extra-android-support
  - extra-android-m2repository
cache:
  directories:
  - MultiHero/app/build/outputs/apk
before_install:
- gem install fir-cli
script:
- cd MultiHero
- chmod +x ./gradlew
- echo  > /home/travis/.android/repositories.cfg
- "./gradlew :app:assembleRelease"
deploy:
  provider: releases
  api_key:
    secure: 3wOLxxHvSxFBOlugP8A9GJbWaTnINF6/ZRukEtoNIzNaGlHJo+y5Y21lNMYZc8b9Ok5hJEFyk8zSyf1qoZ0D/mW2xwhM8lIT1KKgXaRIV9plIgyBq2qJmbIx5HQWiiejfXlpCMdEYEz9jH8ddVTGAAICaniInLDRFoClUl33o+LDTDtuNpNFyaLMRrK3M6QO26HJ0sLfyRa4bHMxtwPLLMz3Dkd9bXFohnZpE3Q7fd9CQpO18qX3HZL/VfBDC9m3A5WneRy6te8fhUOkkoZO7K3rQuBCU9vNUomWCZyiloU2Sbty2B/1iRPj6iLyfiUQTmZCwdNCrJuh321aLEGh3UD1Y/DrHeYWU058KC6dUrNt1bP5eGcbEWCrOuFsxdQDGMzXwilwY59z7pvQU9IdG4w0OsQj5IMihST3ZqTkT0x2nYrnvH+2+SkCKG3pbXdSDdD/DyzLUqcKQAyfc/ImEPi25ApIlqmZU7NZVcOOGvpkJmnkEvEuvN36PXvoGQyqdQiaX2cWYO5cxv+8BqOc9DlmEvb244iW0fxnsFHSSY7J/WRItIdb08CFzqD7P77J3NLgGhK/XHb9orb2IYByocYeY+jJ6GlPoM2HHexHc2Dg8nQC/M6zY2uSUJD8R4ImdthAEKkfZvQvFreBt9Mz7x7VCBxkoxLaLcmjB/j26qM=
  file: ./app/build/outputs/apk/release/app-release-unsigned.apk
  draft: true
  skip_cleanup: true
  tag: false
  on:
    repo: theall/android_examples
after_deploy:
- pwd
- find ./ -name *.apk
- fir p ./app/build/outputs/apk/release/app-release-unsinged.apk -T $FIR_TOKEN -c
  "`git cat-file tag $TRAVIS_TAG`"
