language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-15
  - extra-android-support
  - extra-android-m2repository
  
before_install:
  - chmod +x ./MultiHero/gradlew
  
script:
- ./MultiHero/gradlew :app:assembleRelease

