language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-15
  - extra-android-support
  - extra-android-m2repository
script:
- ./Multihero/gradlew :app:assembleRelease

