language: android
sudo: false
android:
  components:
  - build-tools-28.0.3
  - android-15
  - extra-android-support
  - extra-android-m2repository
  
script:
  - cd MultiHero
  - chmod +x ./gradlew
  - ./gradlew :app:assembleRelease

